### ISSUE TITLE
Account not working

### ISSUE THREAD

**Issue by S3wd11** [OnlyRizzAI/public-tracker#1]
Hello I'm premium member, and I got an issue where's everything is not appearing. Basically I can't do anything.
![Screenshot_20231213-055920_Chrome](https://github.com/OnlyRizzAI/public-tracker/assets/153699313/bfa2ad34-b4a6-40a5-b61a-46256ed5c297)
![Screenshot_20231213-054640_Chrome](https://github.com/OnlyRizzAI/public-tracker/assets/153699313/a83f47de-8db9-4f66-b039-675e00e2d1fc)

**Comment by OnlyRizzAI** [comment]
Hello,

Thank you very much for your report. Our provider had an outage during this time, which caused the issues on your end. It is now resolved, and we are taking action to avoid this in the future. Apologies for any inconvenience!
