### ISSUE TITLE
real direct to bank processing

### ISSUE THREAD

**Issue by captmikes** [OnlyRizzAI/public-tracker#3]
It looks like you could use some robust real merchant services. Please hit  me up if you'd like an intro. Till then i suppose I'll push my affiliates elsewhere.  Otherwise it's a slick site man!

**Comment by OnlyRizzJoe** [comment]
Hey, we are working on payment processing and will let you know once we are back up. Thanks for the compliment!

**Comment by OnlyRizzAI** [comment]
Hey @captmikes, I deleted your comment in this public ticket, but if you can send us an email @ business@onlyrizz.ai .

Thanks!
